### ISSUE TITLE
FileStack plugin Issue 

### ISSUE THREAD

**Issue by BharathSavitr** [artf/grapesjs-plugin-filestack#3]
Hi,
I added fileStack plugin,
<head>
..
  <link rel="stylesheet" href="../core/plugins/grapesjs-plugin-filestack.css">
  <script src="../core/plugins/grapesjs-plugin-filestack.min.js"></script>
...
</head>

var editor = grapesjs.init({
....
plugins: ['gjs-plugin-filestack'],
pluginsOpts: {
        'gjs-plugin-filestack': {
          key: 'A2uS7BnssSUSrxxxxxxx....',

        }
      },
...
});

 it throws an error like

Uncaught ReferenceError: filestack is not defined
    at grapesjs-plugin-filestack.min.js:2
    at grapes.min.js:2
    at Array.forEach (<anonymous>)
    at Object.init (grapes.min.js:2)
    at (index):45

**Comment by artf** [comment]
@BharathSavitr Filestack itself is not included so you have to add it manually
```html
<script src="https://static.filestackapi.com/v3/filestack-0.1.10.js"></script>
```
