### ISSUE TITLE
Unauthorised error, unable to upload from My Device

### ISSUE THREAD

**Issue by faizansaiyed** [artf/grapesjs-plugin-filestack#4]
Hey @artf 
I've integrated FileStack in GrapesJS editor. Other things work fine except, I get this error and not able to upload file from My Device option. Anything missing?
![screenshot from 2017-12-25 12-49-22](https://user-images.githubusercontent.com/33310500/34335082-12175000-e972-11e7-9790-3bfd45c1b760.png)

Here is my code:

```
editor = grapesjs.init({
			plugins: [ [other-plugins ... ], 'gjs-plugin-filestack' ],
            pluginsOpts: {
                'gjs-plugin-filestack': {
                    'key': [my-key],
                    'filestackOpts': {
                        'fromSources':["local_file_system","url","imagesearch","facebook","instagram","googledrive","dropbox","flickr","onedrive"]
                    }
                }
            },
.....
});
```

One more error is :
![screenshot from 2017-12-25 12-46-56](https://user-images.githubusercontent.com/33310500/34335048-c3948d26-e971-11e7-8175-90b1ae4a0460.png)

**Comment by artf** [comment]
@fsaiyedOB your key is wrong, look at the url `apikey=my-key`

**Comment by faizansaiyed** [comment]
I'm passing my key provided from FileStack, just for privacy, I've removed from the screenshot.
I've also specified that everything is working fine except for My Device option. If the key is wrong, nothing will work.

**Comment by artf** [comment]
@fsaiyedOB try to create an upload button without grapesjs, looks like something wrong with FileStack itself

**Comment by faizansaiyed** [comment]
Custom upload button works fine without any errors, but I want it inside Grapes Editor, in assets manager modal.
![image](https://user-images.githubusercontent.com/33310500/34720851-580e7a34-f566-11e7-8bb5-7f559c672c1d.png)

**Comment by artf** [comment]
yeah but from your errors seems like there is an issue with files from FileStack
