### ISSUE TITLE
Uncaught ReferenceError: filestack is not defined

### ISSUE THREAD

**Issue by niamrox** [artf/grapesjs-plugin-filestack#5]
Hi,
Its not running , There JS error , I have installed and linked plugin successfully but still showing error.
  | (anonymous) | @ | grapesjs-plugin-filestack.min.js:2
-- | -- | -- | --
  | (anonymous) | @ | VM243 grapes.min.js:32379
  | init | @ | VM243 grapes.min.js:32375
  | (anonymous) | @ | (index):96

**Comment by artf** [comment]
Just add filestack
```html
<script src="https://static.filestackapi.com/v3/filestack-0.1.10.js"></script>
```

**Comment by niamrox** [comment]
That solve the error but generated another 
Uncaught Error: Filestack's API key not found

  | (anonymous) | @ | grapesjs-plugin-filestack.min.js:2
-- | -- | -- | --
  | (anonymous) | @ | VM94 grapes.min.js:32379
  | init | @ | VM94 grapes.min.js:32375
  | (anonymous) | @ | (index):97

**Comment by artf** [comment]
@niamulrox I think the error is pretty much self-explanatory...

**Comment by Sundaram218** [comment]
**@artf I am also getting the same error as Uncaught Error: Filestack's API key not found. And I don't know how I can solve this error. @artf Kindy help me out with this one. Thanks**
